import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { LayoutProps } from "@/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} flex gap-x-2 h-screen`}
			>
				<Sidebar />
				{children}
			</body>
		</html>
	);
}
